### ISSUE TITLE
Resizing Post Previews?

### ISSUE THREAD

**Issue by adminalec** [charlieasemota/philomina-wp#5]
I was just wondering: in what part of the code is the section to adjust the scaling/croppping of the images shown on the main site (the posts)? I've noticed that the way it's set up, it chops parts of them.

**Comment by thursby** [comment]
I too found this behavior unpredictable and hard to control. It's because it's cropping the images instead of resizing. As long as you can size your images correctly this isn't necessary.
functions.php line 11:

`add_image_size('philomina_featured', 800, 800, true );`

The final argument is whether or not to crop. If `true` then it crops, if `false` it resizes while keeping the aspect ratio. Try changing it to `false` and see if that makes more sense to you. I didn't like the 800px image size either, so I hacked around it completely in a child theme. If you were looking for quick and dirty though, line 11 is it.

**Comment by charlieasemota** [comment]
@adminalec please see @thursby response, being a public theme it's setup for the average user, if you already crop the images before uploading then you should change the value passed to the add_image_size() function.

**Comment by adminalec** [comment]
Hi again! Thank you for the replies!
I tried using a 800px by 800 px image and the image just look pixelated.
I also tried re-writing that line with 'false' and nothing changed at all. Is this not working? :/

**Comment by charlieasemota** [comment]
@adminalec You need to re-upload the images for them to be resized
